name: fix_map
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_cupertino_localizations: ^1.0.1
  equatable: ^1.1.0
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  intl: ^0.16.0
  shared_preferences: 0.5.3+3
  permission_handler: ^4.2.0+hotfix.3
  fluttertoast: ^3.1.3
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^8.7.0
  google_maps_flutter: ^0.5.24
  geolocator: ^5.2.1
  flutter_swiper: 1.1.6
  dio: ^3.0.8
  sqflite: ^1.2.1
  path_provider: ^1.6.0
  cached_network_image: ^2.0.0
  percent_indicator: ^2.1.1+1
  bloc_test: ^3.1.0
  flutter_rating_bar: ^3.0.1+1
  url_launcher: ^5.4.1
  flutter_offline: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_coverage: ^0.4.0
  mockito: ^4.1.1
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/map/circle.png"

flutter:
  uses-material-design: true
  assets:
    - assets/map/
    - assets/onboarding/